name = "ArcParser"
uuid = "40fd6c00-026b-48ee-98ec-938f22357df0"
authors = ["lipid <lipid.l@qq.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
LinearAlgebra = "1"
Random = "1"
julia = "1"
Combinatorics = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
