name = "ArcParser"
uuid = "40fd6c00-026b-48ee-98ec-938f22357df0"
authors = ["lipid <lipid.l@qq.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
